language: node_js

node_js:
  - "0.11"

services:
  - redis-server

install_script: npm install

script: npm test

branches:
  only:
    # Travis will build annotated tags as branches unless we restrict to this
    - master

deploy:
  provider: heroku
  api_key:
    secure: DAUK1W6LYfoE+sdXrPUvq/g90nIFm1at/4rO3eAxbc+7T0MvUSrzwqmC6JaKWJbHKNdfxjsJHqGJZYh6h/ZxDipTUTKt4jQugIl14IoeqzTSmHldnbIxnwqPIaGPTNogxsfCsDcmIK8HsXMjLMRzChGsPOUJM93arlGvjtLZTYI=
  app:
    master: roobot-test
  on:
    repo: gittip/roobot
    tags: true
    # Official hack: http://docs.travis-ci.com/user/deployment/heroku/#Conditional-Deploys
    all_branches: true

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.org#gittip"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
    skip_join: true
